from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any

from . import __version__
from .manifest import OBJECT_CATALOG_SCHEMA_VERSION
from .tactical.places import PLACE_TYPES
from .tactical.runtime_objects import RUNTIME_OBJECT_TYPES

BASE_TILE_TYPES: tuple[dict[str, str], ...] = (
    {
        "symbol": "+",
        "type": "grass",
        "name_ru": "Трава",
        "meaning": "Обычная поверхность карты.",
    },
    {
        "symbol": ".",
        "type": "old_road",
        "name_ru": "Старая дорога",
        "meaning": "Проходимый маршрут и след старой инфраструктуры.",
    },
    {
        "symbol": "T",
        "type": "tree",
        "name_ru": "Дерево",
        "meaning": "Лесной блокер и визуальная масса.",
    },
    {
        "symbol": "b",
        "type": "bush",
        "name_ru": "Куст",
        "meaning": "Растительность и мягкое заполнение лесных краёв.",
    },
    {
        "symbol": "f",
        "type": "flower_patch",
        "name_ru": "Цветы / заросли",
        "meaning": "Декоративная вариативность поверхности.",
    },
    {
        "symbol": "m",
        "type": "mushroom_patch",
        "name_ru": "Грибы",
        "meaning": "Биомный декоративный маркер.",
    },
    {
        "symbol": "w",
        "type": "water_puddle",
        "name_ru": "Вода / лужа",
        "meaning": "Низина, лужа или водная помеха.",
    },
    {
        "symbol": "c",
        "type": "cracked_ground",
        "name_ru": "Потрескавшаяся земля",
        "meaning": "Разрушенная или высохшая поверхность.",
    },
    {
        "symbol": "#",
        "type": "ruin_wall",
        "name_ru": "Руинная стена",
        "meaning": "Фрагмент стены, жёсткий блокер.",
    },
    {
        "symbol": "R",
        "type": "ruin_floor",
        "name_ru": "Руинный пол",
        "meaning": "Площадка старой постройки или руин.",
    },
    {
        "symbol": "S",
        "type": "start",
        "name_ru": "Старт",
        "meaning": "Стартовая точка карты.",
    },
    {
        "symbol": "G",
        "type": "goal",
        "name_ru": "Цель",
        "meaning": "Целевая точка карты.",
    },
)

RUNTIME_DEBUG_SYMBOLS: dict[str, str] = {
    "fallen_log": "L",
    "stone_chunk": "K",
    "bush_thicket": "B",
    "scrap_pile": "X",
    "rusted_barrel": "E",
    "ammo_cache": "A",
    "medkit_cache": "H",
    "trench": "U",
    "big_dead_tree": "D",
    "broken_radio_mast": "N",
    "old_checkpoint": "O",
    "car_wreck": "V",
    "abandoned_backpack": "P",
    "field_tent": "T",
    "dead_campfire": "F",
    "broken_generator": "J",
    "cable_spool": "C",
    "warning_sign": "W",
    "old_grave_marker": "Z",
    "pit": "I",
    "earth_berm": "Q",
    "old_well": "M",
    "abandoned_cart": "Y",
}


def write_object_catalog(
    *,
    path: Path,
    rows: list[str],
    runtime_data: dict[str, Any],
) -> None:
    """Write a human-readable generated object catalog.

    Args:
        path: Destination Markdown path.
        rows: Generated ASCII map rows.
        runtime_data: Runtime tactical map data.
    """
    path.write_text(
        build_object_catalog_markdown(rows=rows, runtime_data=runtime_data),
        encoding="utf-8",
    )


def build_object_catalog_markdown(
    *,
    rows: list[str],
    runtime_data: dict[str, Any],
) -> str:
    """Build a human-readable generated object catalog.

    Args:
        rows: Generated ASCII map rows.
        runtime_data: Runtime tactical map data.

    Returns:
        Markdown document.
    """
    runtime_counts = _runtime_object_counts(runtime_data)
    tile_counts = _tile_counts(rows, runtime_data)
    place_counts = _place_counts(runtime_data)

    lines = [
        "# Object Catalog",
        "",
        f"Generated by TopDownMapGen v{__version__}.",
        "",
        f"Schema version: `{OBJECT_CATALOG_SCHEMA_VERSION}`.",
        "",
        "Этот файл предназначен для человека: он расшифровывает символы, типы объектов и показывает фактическое количество сущностей в текущей генерации.",
        "",
        "## Runtime objects generated in this run",
        "",
    ]
    runtime_rows: list[list[str]] = []
    for spec in RUNTIME_OBJECT_TYPES:
        object_type = str(spec["type"])
        runtime_rows.append(
            [
                RUNTIME_DEBUG_SYMBOLS.get(object_type, "?"),
                f"`{object_type}`",
                str(spec.get("name_ru", object_type)),
                f"`{spec.get('role', 'unknown')}`",
                str(runtime_counts.get(object_type, 0)),
                _runtime_object_meaning(object_type),
            ],
        )
    lines.extend(
        _markdown_table(
            headers=["Symbol", "Type", "Russian name", "Role", "Count", "Meaning"],
            rows=runtime_rows,
            right_aligned={"Count"},
        ),
    )

    lines.extend(
        [
            "",
            "## Base map tiles generated in this run",
            "",
        ],
    )
    tile_rows: list[list[str]] = []
    for spec in BASE_TILE_TYPES:
        symbol = spec["symbol"]
        tile_rows.append(
            [
                f"`{symbol}`",
                f"`{spec['type']}`",
                spec["name_ru"],
                str(tile_counts.get(symbol, 0)),
                spec["meaning"],
            ],
        )
    lines.extend(
        _markdown_table(
            headers=["Symbol", "Type", "Russian name", "Count", "Meaning"],
            rows=tile_rows,
            right_aligned={"Count"},
        ),
    )

    lines.extend(
        [
            "",
            "## Places generated in this run",
            "",
        ],
    )
    place_rows: list[list[str]] = []
    for spec in PLACE_TYPES:
        place_type = str(spec["type"])
        place_rows.append(
            [
                f"`{place_type}`",
                str(spec.get("name_ru", place_type)),
                str(place_counts.get(place_type, 0)),
                f"`{spec.get('role', 'unknown')}`",
            ],
        )
    lines.extend(
        _markdown_table(
            headers=["Type", "Russian name", "Count", "Role"],
            rows=place_rows,
            right_aligned={"Count"},
        ),
    )

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- `layer_base_map.png` показывает базовую тайловую карту.",
            "- `layer_runtime_objects.png` показывает runtime/gameplay objects.",
            "- `layer_all_debug.png` показывает общий debug-overlay, если запуск был с `--include-debug-layers`.",
            "- Полные машинные данные лежат в `tactical_map.json`.",
            "",
        ],
    )
    return "\n".join(lines)


def _markdown_table(
    *,
    headers: list[str],
    rows: list[list[str]],
    right_aligned: set[str] | None = None,
) -> list[str]:
    """Build an aligned Markdown table.

    Args:
        headers: Table column names.
        rows: Table rows.
        right_aligned: Column names that should be right-aligned.

    Returns:
        Markdown lines with padded cells.
    """
    right_aligned = right_aligned or set()
    widths = _table_widths(headers, rows)
    header_line = _format_table_row(headers, widths, right_aligned=set())
    separator_line = _format_separator_row(headers, widths, right_aligned)
    body_lines = [
        _format_table_row(row, widths, right_aligned=right_aligned, headers=headers)
        for row in rows
    ]
    return [header_line, separator_line, *body_lines]


def _table_widths(headers: list[str], rows: list[list[str]]) -> list[int]:
    widths = [_display_width(header) for header in headers]
    for row in rows:
        for index, cell in enumerate(row):
            widths[index] = max(widths[index], _display_width(cell))
    return widths


def _format_table_row(
    cells: list[str],
    widths: list[int],
    *,
    right_aligned: set[str],
    headers: list[str] | None = None,
) -> str:
    padded_cells: list[str] = []
    for index, cell in enumerate(cells):
        header = headers[index] if headers is not None else cell
        padded_cells.append(
            _pad_cell(cell, widths[index], align_right=header in right_aligned),
        )
    return f"| {' | '.join(padded_cells)} |"


def _format_separator_row(
    headers: list[str],
    widths: list[int],
    right_aligned: set[str],
) -> str:
    cells = []
    for header, width in zip(headers, widths, strict=True):
        dash_count = max(width, 3)
        if header in right_aligned:
            cells.append(f"{'-' * (dash_count - 1)}:")
        else:
            cells.append('-' * dash_count)
    return f"| {' | '.join(cells)} |"


def _pad_cell(value: str, width: int, *, align_right: bool) -> str:
    padding = max(width - _display_width(value), 0)
    if align_right:
        return f"{' ' * padding}{value}"
    return f"{value}{' ' * padding}"


def _display_width(value: str) -> int:
    return len(value)


def _runtime_object_counts(runtime_data: dict[str, Any]) -> dict[str, int]:
    summary = runtime_data.get("runtime_objects_summary")
    if isinstance(summary, dict) and isinstance(summary.get("by_type"), dict):
        return _int_dict(summary["by_type"])
    return dict(
        Counter(
            str(item.get("type"))
            for item in _dict_list(runtime_data.get("runtime_objects"))
            if item.get("type") is not None
        ),
    )


def _tile_counts(rows: list[str], runtime_data: dict[str, Any]) -> dict[str, int]:
    map_data = runtime_data.get("map")
    if isinstance(map_data, dict) and isinstance(map_data.get("tile_counts"), dict):
        return _int_dict(map_data["tile_counts"])
    return dict(Counter("".join(rows)))


def _place_counts(runtime_data: dict[str, Any]) -> dict[str, int]:
    summary = runtime_data.get("places_summary")
    if isinstance(summary, dict) and isinstance(summary.get("by_type"), dict):
        return _int_dict(summary["by_type"])
    return dict(
        Counter(
            str(item.get("type"))
            for item in _dict_list(runtime_data.get("places"))
            if item.get("type") is not None
        ),
    )


def _runtime_object_meaning(object_type: str) -> str:
    meanings = {
        "fallen_log": "Низкое/частичное укрытие и природное препятствие.",
        "stone_chunk": "Жёсткое укрытие и каменный блокер.",
        "bush_thicket": "Мягкое укрытие, маскировка и заросли.",
        "scrap_pile": "Обломки, металлолом и частичное укрытие.",
        "rusted_barrel": "Рискованный объект, кандидат на будущую опасность/взрыв.",
        "ammo_cache": "Точка интереса и потенциальный ресурс.",
        "medkit_cache": "Точка интереса и потенциальное лечение.",
        "trench": "Углубление уровня -1 и защитная микроструктура.",
        "big_dead_tree": "Высокий landmark и природный ориентир.",
        "broken_radio_mast": "Landmark, след связи или экспедиции.",
        "old_checkpoint": "Блокпост, defensive landmark и след старого контроля.",
        "car_wreck": "Остов автомобиля, дорожный техногенный след и частичное укрытие.",
        "abandoned_backpack": "Брошенный рюкзак, малый человеческий след и потенциальная точка интереса.",
        "field_tent": "Полевая палатка, основа лагерной микросцены.",
        "dead_campfire": "Потухший костёр, маркер старой стоянки.",
        "broken_generator": "Сломанный генератор, техногенный мусор и след экспедиции.",
        "cable_spool": "Кабельная катушка, технический мусор и низкое укрытие.",
        "warning_sign": "Предупреждающий знак, маркер запретной или опасной области.",
        "old_grave_marker": "Старая могила или крест, тревожный story marker.",
        "pit": "Провал или яма уровня -1, локальная низина.",
        "earth_berm": "Земляная насыпь, мягкий рельеф и низкое укрытие.",
        "old_well": "Колодец, story landmark для заброшенных мест.",
        "abandoned_cart": "Брошенная тележка, дорожный след и частичное укрытие.",
    }
    return meanings.get(object_type, "Runtime object.")


def _dict_list(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]


def _int_dict(value: dict[Any, Any]) -> dict[str, int]:
    result: dict[str, int] = {}
    for key, raw_count in value.items():
        try:
            result[str(key)] = int(raw_count)
        except (TypeError, ValueError):
            result[str(key)] = 0
    return result
