from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any

from . import __version__
from .manifest import OBJECT_CATALOG_SCHEMA_VERSION
from .tactical.places import PLACE_TYPES
from .tactical.runtime_objects import RUNTIME_OBJECT_TYPES

BASE_TILE_TYPES: tuple[dict[str, str], ...] = (
    {
        "symbol": "+",
        "type": "grass",
        "name_ru": "Трава",
        "meaning": "Обычная поверхность карты.",
    },
    {
        "symbol": ".",
        "type": "old_road",
        "name_ru": "Старая дорога",
        "meaning": "Проходимый маршрут и след старой инфраструктуры.",
    },
    {
        "symbol": "T",
        "type": "tree",
        "name_ru": "Дерево",
        "meaning": "Лесной блокер и визуальная масса.",
    },
    {
        "symbol": "b",
        "type": "bush",
        "name_ru": "Куст",
        "meaning": "Растительность и мягкое заполнение лесных краёв.",
    },
    {
        "symbol": "f",
        "type": "flower_patch",
        "name_ru": "Цветы / заросли",
        "meaning": "Декоративная вариативность поверхности.",
    },
    {
        "symbol": "m",
        "type": "mushroom_patch",
        "name_ru": "Грибы",
        "meaning": "Биомный декоративный маркер.",
    },
    {
        "symbol": "w",
        "type": "water_puddle",
        "name_ru": "Вода / лужа",
        "meaning": "Низина, лужа или водная помеха.",
    },
    {
        "symbol": "c",
        "type": "cracked_ground",
        "name_ru": "Потрескавшаяся земля",
        "meaning": "Разрушенная или высохшая поверхность.",
    },
    {
        "symbol": "#",
        "type": "ruin_wall",
        "name_ru": "Руинная стена",
        "meaning": "Фрагмент стены, жёсткий блокер.",
    },
    {
        "symbol": "R",
        "type": "ruin_floor",
        "name_ru": "Руинный пол",
        "meaning": "Площадка старой постройки или руин.",
    },
    {
        "symbol": "S",
        "type": "start",
        "name_ru": "Старт",
        "meaning": "Стартовая точка карты.",
    },
    {
        "symbol": "G",
        "type": "goal",
        "name_ru": "Цель",
        "meaning": "Целевая точка карты.",
    },
)

RUNTIME_DEBUG_SYMBOLS: dict[str, str] = {
    "fallen_log": "L",
    "stone_chunk": "K",
    "bush_thicket": "B",
    "scrap_pile": "X",
    "rusted_barrel": "E",
    "ammo_cache": "A",
    "medkit_cache": "H",
    "trench": "U",
    "big_dead_tree": "D",
    "broken_radio_mast": "N",
    "old_checkpoint": "O",
}


def write_object_catalog(
    *,
    path: Path,
    rows: list[str],
    runtime_data: dict[str, Any],
) -> None:
    """Write a human-readable generated object catalog.

    Args:
        path: Destination Markdown path.
        rows: Generated ASCII map rows.
        runtime_data: Runtime tactical map data.
    """
    path.write_text(
        build_object_catalog_markdown(rows=rows, runtime_data=runtime_data),
        encoding="utf-8",
    )


def build_object_catalog_markdown(
    *,
    rows: list[str],
    runtime_data: dict[str, Any],
) -> str:
    """Build a human-readable generated object catalog.

    Args:
        rows: Generated ASCII map rows.
        runtime_data: Runtime tactical map data.

    Returns:
        Markdown document.
    """
    runtime_counts = _runtime_object_counts(runtime_data)
    tile_counts = _tile_counts(rows, runtime_data)
    place_counts = _place_counts(runtime_data)

    lines = [
        "# Object Catalog",
        "",
        f"Generated by TopDownMapGen v{__version__}.",
        "",
        f"Schema version: `{OBJECT_CATALOG_SCHEMA_VERSION}`.",
        "",
        "Этот файл предназначен для человека: он расшифровывает символы, типы объектов и показывает фактическое количество сущностей в текущей генерации.",
        "",
        "## Runtime objects generated in this run",
        "",
        "| Symbol | Type | Russian name | Role | Count | Meaning |",
        "|---|---|---|---|---:|---|",
    ]
    for spec in RUNTIME_OBJECT_TYPES:
        object_type = str(spec["type"])
        lines.append(
            "| {symbol} | `{type}` | {name_ru} | `{role}` | {count} | {meaning} |".format(
                symbol=RUNTIME_DEBUG_SYMBOLS.get(object_type, "?"),
                type=object_type,
                name_ru=str(spec.get("name_ru", object_type)),
                role=str(spec.get("role", "unknown")),
                count=runtime_counts.get(object_type, 0),
                meaning=_runtime_object_meaning(object_type),
            ),
        )

    lines.extend(
        [
            "",
            "## Base map tiles generated in this run",
            "",
            "| Symbol | Type | Russian name | Count | Meaning |",
            "|---|---|---|---:|---|",
        ],
    )
    for spec in BASE_TILE_TYPES:
        symbol = spec["symbol"]
        lines.append(
            "| `{symbol}` | `{type}` | {name_ru} | {count} | {meaning} |".format(
                symbol=symbol,
                type=spec["type"],
                name_ru=spec["name_ru"],
                count=tile_counts.get(symbol, 0),
                meaning=spec["meaning"],
            ),
        )

    lines.extend(
        [
            "",
            "## Places generated in this run",
            "",
            "| Type | Russian name | Count | Role |",
            "|---|---|---:|---|",
        ],
    )
    for spec in PLACE_TYPES:
        place_type = str(spec["type"])
        lines.append(
            "| `{type}` | {name_ru} | {count} | `{role}` |".format(
                type=place_type,
                name_ru=str(spec.get("name_ru", place_type)),
                count=place_counts.get(place_type, 0),
                role=str(spec.get("role", "unknown")),
            ),
        )

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- `layer_base_map.png` показывает базовую тайловую карту.",
            "- `layer_runtime_objects.png` показывает runtime/gameplay objects.",
            "- `layer_all_debug.png` показывает общий debug-overlay, если запуск был с `--include-debug-layers`.",
            "- Полные машинные данные лежат в `tactical_map.json`.",
            "",
        ],
    )
    return "\n".join(lines)


def _runtime_object_counts(runtime_data: dict[str, Any]) -> dict[str, int]:
    summary = runtime_data.get("runtime_objects_summary")
    if isinstance(summary, dict) and isinstance(summary.get("by_type"), dict):
        return _int_dict(summary["by_type"])
    return dict(
        Counter(
            str(item.get("type"))
            for item in _dict_list(runtime_data.get("runtime_objects"))
            if item.get("type") is not None
        ),
    )


def _tile_counts(rows: list[str], runtime_data: dict[str, Any]) -> dict[str, int]:
    map_data = runtime_data.get("map")
    if isinstance(map_data, dict) and isinstance(map_data.get("tile_counts"), dict):
        return _int_dict(map_data["tile_counts"])
    return dict(Counter("".join(rows)))


def _place_counts(runtime_data: dict[str, Any]) -> dict[str, int]:
    summary = runtime_data.get("places_summary")
    if isinstance(summary, dict) and isinstance(summary.get("by_type"), dict):
        return _int_dict(summary["by_type"])
    return dict(
        Counter(
            str(item.get("type"))
            for item in _dict_list(runtime_data.get("places"))
            if item.get("type") is not None
        ),
    )


def _runtime_object_meaning(object_type: str) -> str:
    meanings = {
        "fallen_log": "Низкое/частичное укрытие и природное препятствие.",
        "stone_chunk": "Жёсткое укрытие и каменный блокер.",
        "bush_thicket": "Мягкое укрытие, маскировка и заросли.",
        "scrap_pile": "Обломки, металлолом и частичное укрытие.",
        "rusted_barrel": "Рискованный объект, кандидат на будущую опасность/взрыв.",
        "ammo_cache": "Точка интереса и потенциальный ресурс.",
        "medkit_cache": "Точка интереса и потенциальное лечение.",
        "trench": "Углубление уровня -1 и защитная микроструктура.",
        "big_dead_tree": "Высокий landmark и природный ориентир.",
        "broken_radio_mast": "Landmark, след связи или экспедиции.",
        "old_checkpoint": "Блокпост, defensive landmark и след старого контроля.",
    }
    return meanings.get(object_type, "Runtime object.")


def _dict_list(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, list):
        return []
    return [item for item in value if isinstance(item, dict)]


def _int_dict(value: dict[Any, Any]) -> dict[str, int]:
    result: dict[str, int] = {}
    for key, raw_count in value.items():
        try:
            result[str(key)] = int(raw_count)
        except (TypeError, ValueError):
            result[str(key)] = 0
    return result
